name = "ics"
version = "0.1.0"

description = "Ics Calendar compliant with RFC2445"
licences = ["MIT"]
repository = { type = "github", user = "nicklayb", repo = "gleam_ics" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_regexp = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
